name: emotionpot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  riverpod: ^2.6.1
  sqflite: ^2.4.1
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/

  fonts:
    - family: NanumPen
      fonts:
        - asset: assets/fonts/NanumPen.otf
    - family: Bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf
    - family: Regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
    - family: Light
      fonts:
        - asset: assets/fonts/Pretendard-Light.otf
    - family: Medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf
